### ISSUE TITLE
[Bug] Gain 1 more row than expected, from query on session_state.session_level_memory_consumption

### ISSUE THREAD

**Issue by congxuebin** [cloudberrydb/cloudberrydb#253]
### What happened

2 Test cases in CBDBTesrepo Failed

FAIL: RunawayDetectorTestCase.test_runaway_detected_by_other

Traceback (most recent call last):
  File "/code/cbdb_testrepo_src/mpp/models/sql_tc.py", line 489, in implied_test_function
    result = my_self.run_test()
  File "/code/cbdb_testrepo_src/mpp/models/sql_tc.py", line 668, in run_test
    self._run_and_verify_sql_file(sql_file, self._current_optimizer_mode)
  File "/code/cbdb_testrepo_src/mpp/models/sql_tc.py", line 725, in _run_and_verify_sql_file
    ans_file))
AssertionError: Failed: diffs during execution of sql: /code/cbdb_testrepo_src/resource_management/runaway_query/runaway_detector/sql/runaway_detected_by_other.sql, out_file: /code/cbdb_testrepo_src/resource_management/runaway_query/runaway_detector/output/runaway_detected_by_other.out, ans_file: /code/cbdb_testrepo_src/resource_management/runaway_query/runaway_detector/expected/runaway_detected_by_other.ans

FAIL: RunawayDetectorTestCase.test_runaway_detects_itself 

Traceback (most recent call last):
  File "/code/cbdb_testrepo_src/mpp/models/sql_tc.py", line 489, in implied_test_function
    result = my_self.run_test()
  File "/code/cbdb_testrepo_src/mpp/models/sql_tc.py", line 668, in run_test
    self._run_and_verify_sql_file(sql_file, self._current_optimizer_mode)
  File "/code/cbdb_testrepo_src/mpp/models/sql_tc.py", line 725, in _run_and_verify_sql_file
    ans_file))
AssertionError: Failed: diffs during execution of sql: /code/cbdb_testrepo_src/resource_management/runaway_query/runaway_detector/sql/runaway_detects_itself.sql, out_file: /code/cbdb_testrepo_src/resource_management/runaway_query/runaway_detector/output/runaway_detects_itself.out, ans_file: /code/cbdb_testrepo_src/resource_management/runaway_query/runaway_detector/expected/runaway_detects_itself.ans

------
I believe they are from the same root cause.  More detailed information about this issue:
----

Test case expects 7 rows from this query. 

```
-- To create the session_state.session_level_memory_consumption view
CREATE EXTENSION gp_internal_tools;
CREATE
-- end_ignore

-- Check to see that there is only one session running
1: select count(*) from session_state.session_level_memory_consumption where segid = -1;
count
-----
    7
(1 row)
```

But new behavior, it gets 8 rows. 

```
CREATE EXTENSION gp_internal_tools; 
CREATE
-- end_ignore 

-- Check to see that there is only one session running 
1: select count(*) from session_state.session_level_memory_consumption where segid = -1; 
count
-----
    8
(1 row)
```

I figured out a way to get detailed data, please reference to the following files. 

[session_level_memory_consumption_new.txt](https://github.com/cloudberrydb/cloudberrydb/files/13049045/session_level_memory_consumption_new.txt)

[session_level_memory_consumption_old.txt](https://github.com/cloudberrydb/cloudberrydb/files/13049051/session_level_memory_consumption_old.txt)

### What you think should happen instead

As I mentioned above

### How to reproduce

https://code.hashdata.xyz/cloudberry/cbdb_testrepo/-/pipelines/52870

Run "sql-p1"， find the IP address in the output.

Login the machine with the IP address.

Issue the following statements:

su - gpadmin
source /usr/local/cloudberry-db-devel/greenplum_path.sh
source /code/gpdb_src/gpAux/gpdemo/gpdemo-env.sh
source /code/cbdb_testrepo_src/test_framework/tinc_env.sh
source /code/cbdb_testrepo_src/tincrepo_env.sh

cd /code/cbdb_testrepo_src

/code/cbdb_testrepo_src/test_framework/tinc.py discover resource_management/runaway_query

You will see the first 2 test cases are running and then get the failure output.

Please note, the machine can keep alive in 5 hours

### Operating System

centos7

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by congxuebin** [comment]
As talked with Max, this is expected behavior change, I will change test case for this.

**Comment by congxuebin** [comment]
Confirmed with Wenchao,  one more backend thread is involved, thus this behavior is expected. https://github.com/cloudberrydb/cloudberrydb/pull/107
